# Generated by Django 3.1.8 on 2021-09-23 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210923_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='catid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.category'),
        ),
    ]
