# Generated by Django 3.1.8 on 2021-09-23 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210923_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='catid',
        ),
    ]
