# Generated by Django 3.1.8 on 2021-10-07 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20211007_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartproduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.IntegerField(default=1)),
                ('cartid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.cart')),
                ('pid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.products')),
            ],
        ),
    ]
