# Generated by Django 3.1.8 on 2021-10-17 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0011_cartproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymenttype', models.CharField(max_length=4)),
                ('deliverystatus', models.BooleanField(default=False)),
                ('deliverytime', models.DateTimeField()),
                ('custid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='orderproduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.IntegerField(default=1)),
                ('orderid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.order')),
                ('pid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.products')),
            ],
        ),
    ]
